<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
		<Compile Include="../../Scripts/Inventory/*.cs" />
		<Compile Include="../../Scripts/Equipment/EquipmentInstance.cs" />
  </ItemGroup>
</Project>
